let images = [
    {
        url: 'https://img.freepik.com/premium-photo/unique-collection-stylized-scribble-patterns-earth-tones-with-detailed-textures_1137529-60362.jpg?w=900',
        alt: 'Unique collection of stylized scribble patterns in earth tones with detailed textures'
    },
    {
        url: 'https://img.freepik.com/free-photo/abstract-multi-colored-illustration-nature-vibrant-beauty-generated-by-ai_188544-15591.jpg?w=900&t=st=1722456273~exp=1722456873~hmac=9dcaf3ae4fc339afa1ec12863678dd9fd1c4f39d0e81e0a516e1c0af3db77ba5',
        alt: 'Abstract multi-colored illustration of nature with vibrant beauty generated by AI'
    },
    {
        url: 'https://img.freepik.com/free-photo/vibrant-colors-flow-abstract-wave-pattern-generated-by-ai_188544-9781.jpg?w=900&t=st=1722456305~exp=1722456905~hmac=6110460f85ccdc44212c698f15e484b8e05bf628b97605803ec4128eaeb342fa',
        alt: 'Vibrant colors flow in an abstract wave pattern generated by AI'
    },
    {
        url: 'https://img.freepik.com/free-vector/gradient-light-peach-background_52683-110647.jpg?t=st=1722456387~exp=1722459987~hmac=8210d9c7ef358bb11df87f5b8f45440169bbeb6072c703bac438b9ea18645924&w=740',
        alt: 'Gradient light peach background'
    },
    {
        url: 'https://img.freepik.com/free-vector/gradient-geometric-abstract-background_23-2149577017.jpg?t=st=1722456415~exp=1722460015~hmac=286af9c6c78dc5eaf997a5f194287b742c8d4fdb0cc53f2af53de6a6dba76c5b&w=740',
        alt: 'Gradient geometric abstract background'
    },
    {
        url: 'https://img.freepik.com/free-vector/realistic-neon-light-podium-background_52683-87987.jpg?t=st=1722456451~exp=1722460051~hmac=e3d11ef2e8ca5281016f8c14bdab46a16014528ce3e1ef04aadd8e5956ec5e6f&w=740',
        alt: 'Realistic neon light podium background'
    },
    {
        url: 'https://img.freepik.com/free-vector/abstract-3d-black-techno-background-overlap-layers_206725-668.jpg?t=st=1722456470~exp=1722460070~hmac=bafeeddb94769c777eefd90d821dd4e83b6871173f2e1af91b5831d51d79ca8e&w=826',
        alt: 'Abstract 3D black techno background with overlap layers'
    },
    {
        url: 'https://img.freepik.com/free-vector/realistic-golden-dark-podium-background_52683-96823.jpg?t=st=1722456514~exp=1722460114~hmac=e45c295018fbd0f4501bbda515f449950219e69e7711c0101fc8ee1114f8eb46&w=740',
        alt: 'Realistic golden and dark podium background'
    },
    {
        url: 'https://img.freepik.com/free-vector/realistic-pink-silver-background_23-2150057766.jpg?t=st=1722456541~exp=1722460141~hmac=f52cf74ca44ce1718069e47f8a92580ce798b6f848b94e7411b8eb63e3e45512&w=740',
        alt: 'Realistic pink and silver background'
    },
    {
        url: 'https://img.freepik.com/premium-photo/abstract-3d-digital-illustration-infographic-vector-illustration-can-be-used-workflow-layout-diagram-number-options-web-design_475577-67493.jpg?w=740',
        alt: 'Abstract 3D digital illustration infographic vector for workflow layout and web design'
    },
    {
        url: 'https://img.freepik.com/premium-photo/workflow-program-screen-desktop-computer-modern-office_1263944-20.jpg?w=900',
        alt: 'Workflow program screen on desktop computer in a modern office'
    }
];
export default images;
